/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cma

import (
	"encoding/json"
)

// TransportCallAllOf1 struct for TransportCallAllOf1
type TransportCallAllOf1 struct {
	// The code of the service for which the schedule details are published.
	CarrierServiceCode *string `json:"carrierServiceCode,omitempty"`
}

// NewTransportCallAllOf1 instantiates a new TransportCallAllOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf1() *TransportCallAllOf1 {
	this := TransportCallAllOf1{}
	return &this
}

// NewTransportCallAllOf1WithDefaults instantiates a new TransportCallAllOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf1WithDefaults() *TransportCallAllOf1 {
	this := TransportCallAllOf1{}
	return &this
}

// GetCarrierServiceCode returns the CarrierServiceCode field value if set, zero value otherwise.
func (o *TransportCallAllOf1) GetCarrierServiceCode() string {
	if o == nil || o.CarrierServiceCode == nil {
		var ret string
		return ret
	}
	return *o.CarrierServiceCode
}

// GetCarrierServiceCodeOk returns a tuple with the CarrierServiceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf1) GetCarrierServiceCodeOk() (*string, bool) {
	if o == nil || o.CarrierServiceCode == nil {
		return nil, false
	}
	return o.CarrierServiceCode, true
}

// HasCarrierServiceCode returns a boolean if a field has been set.
func (o *TransportCallAllOf1) HasCarrierServiceCode() bool {
	if o != nil && o.CarrierServiceCode != nil {
		return true
	}

	return false
}

// SetCarrierServiceCode gets a reference to the given string and assigns it to the CarrierServiceCode field.
func (o *TransportCallAllOf1) SetCarrierServiceCode(v string) {
	o.CarrierServiceCode = &v
}

func (o TransportCallAllOf1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CarrierServiceCode != nil {
		toSerialize["carrierServiceCode"] = o.CarrierServiceCode
	}
	return json.Marshal(toSerialize)
}

type NullableTransportCallAllOf1 struct {
	value *TransportCallAllOf1
	isSet bool
}

func (v NullableTransportCallAllOf1) Get() *TransportCallAllOf1 {
	return v.value
}

func (v *NullableTransportCallAllOf1) Set(val *TransportCallAllOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf1(val *TransportCallAllOf1) *NullableTransportCallAllOf1 {
	return &NullableTransportCallAllOf1{value: val, isSet: true}
}

func (v NullableTransportCallAllOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


