/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cma

import (
	"encoding/json"
)

// BaseTransportEventAllOf4 struct for BaseTransportEventAllOf4
type BaseTransportEventAllOf4 struct {
	// Free text information provided by the vessel operator regarding the reasons for the change in schedule and/or plans to mitigate schedule slippage.
	ChangeRemark *string `json:"changeRemark,omitempty"`
}

// NewBaseTransportEventAllOf4 instantiates a new BaseTransportEventAllOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseTransportEventAllOf4() *BaseTransportEventAllOf4 {
	this := BaseTransportEventAllOf4{}
	return &this
}

// NewBaseTransportEventAllOf4WithDefaults instantiates a new BaseTransportEventAllOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseTransportEventAllOf4WithDefaults() *BaseTransportEventAllOf4 {
	this := BaseTransportEventAllOf4{}
	return &this
}

// GetChangeRemark returns the ChangeRemark field value if set, zero value otherwise.
func (o *BaseTransportEventAllOf4) GetChangeRemark() string {
	if o == nil || o.ChangeRemark == nil {
		var ret string
		return ret
	}
	return *o.ChangeRemark
}

// GetChangeRemarkOk returns a tuple with the ChangeRemark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTransportEventAllOf4) GetChangeRemarkOk() (*string, bool) {
	if o == nil || o.ChangeRemark == nil {
		return nil, false
	}
	return o.ChangeRemark, true
}

// HasChangeRemark returns a boolean if a field has been set.
func (o *BaseTransportEventAllOf4) HasChangeRemark() bool {
	if o != nil && o.ChangeRemark != nil {
		return true
	}

	return false
}

// SetChangeRemark gets a reference to the given string and assigns it to the ChangeRemark field.
func (o *BaseTransportEventAllOf4) SetChangeRemark(v string) {
	o.ChangeRemark = &v
}

func (o BaseTransportEventAllOf4) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ChangeRemark != nil {
		toSerialize["changeRemark"] = o.ChangeRemark
	}
	return json.Marshal(toSerialize)
}

type NullableBaseTransportEventAllOf4 struct {
	value *BaseTransportEventAllOf4
	isSet bool
}

func (v NullableBaseTransportEventAllOf4) Get() *BaseTransportEventAllOf4 {
	return v.value
}

func (v *NullableBaseTransportEventAllOf4) Set(val *BaseTransportEventAllOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseTransportEventAllOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseTransportEventAllOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseTransportEventAllOf4(val *BaseTransportEventAllOf4) *NullableBaseTransportEventAllOf4 {
	return &NullableBaseTransportEventAllOf4{value: val, isSet: true}
}

func (v NullableBaseTransportEventAllOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseTransportEventAllOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


