/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cma

import (
	"encoding/json"
)

// LocationAllOf struct for LocationAllOf
type LocationAllOf struct {
	// The name of the location.
	LocationName *string `json:"locationName,omitempty"`
}

// NewLocationAllOf instantiates a new LocationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationAllOf() *LocationAllOf {
	this := LocationAllOf{}
	return &this
}

// NewLocationAllOfWithDefaults instantiates a new LocationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationAllOfWithDefaults() *LocationAllOf {
	this := LocationAllOf{}
	return &this
}

// GetLocationName returns the LocationName field value if set, zero value otherwise.
func (o *LocationAllOf) GetLocationName() string {
	if o == nil || o.LocationName == nil {
		var ret string
		return ret
	}
	return *o.LocationName
}

// GetLocationNameOk returns a tuple with the LocationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationAllOf) GetLocationNameOk() (*string, bool) {
	if o == nil || o.LocationName == nil {
		return nil, false
	}
	return o.LocationName, true
}

// HasLocationName returns a boolean if a field has been set.
func (o *LocationAllOf) HasLocationName() bool {
	if o != nil && o.LocationName != nil {
		return true
	}

	return false
}

// SetLocationName gets a reference to the given string and assigns it to the LocationName field.
func (o *LocationAllOf) SetLocationName(v string) {
	o.LocationName = &v
}

func (o LocationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LocationName != nil {
		toSerialize["locationName"] = o.LocationName
	}
	return json.Marshal(toSerialize)
}

type NullableLocationAllOf struct {
	value *LocationAllOf
	isSet bool
}

func (v NullableLocationAllOf) Get() *LocationAllOf {
	return v.value
}

func (v *NullableLocationAllOf) Set(val *LocationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationAllOf(val *LocationAllOf) *NullableLocationAllOf {
	return &NullableLocationAllOf{value: val, isSet: true}
}

func (v NullableLocationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


