/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cma

import (
	"encoding/json"
)

// TransportCallAllOf11 struct for TransportCallAllOf11
type TransportCallAllOf11 struct {
	// An alternative way to capture the facility when no standardized DCSA facility code can be found.
	OtherFacility *string `json:"otherFacility,omitempty"`
}

// NewTransportCallAllOf11 instantiates a new TransportCallAllOf11 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf11() *TransportCallAllOf11 {
	this := TransportCallAllOf11{}
	return &this
}

// NewTransportCallAllOf11WithDefaults instantiates a new TransportCallAllOf11 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf11WithDefaults() *TransportCallAllOf11 {
	this := TransportCallAllOf11{}
	return &this
}

// GetOtherFacility returns the OtherFacility field value if set, zero value otherwise.
func (o *TransportCallAllOf11) GetOtherFacility() string {
	if o == nil || o.OtherFacility == nil {
		var ret string
		return ret
	}
	return *o.OtherFacility
}

// GetOtherFacilityOk returns a tuple with the OtherFacility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf11) GetOtherFacilityOk() (*string, bool) {
	if o == nil || o.OtherFacility == nil {
		return nil, false
	}
	return o.OtherFacility, true
}

// HasOtherFacility returns a boolean if a field has been set.
func (o *TransportCallAllOf11) HasOtherFacility() bool {
	if o != nil && o.OtherFacility != nil {
		return true
	}

	return false
}

// SetOtherFacility gets a reference to the given string and assigns it to the OtherFacility field.
func (o *TransportCallAllOf11) SetOtherFacility(v string) {
	o.OtherFacility = &v
}

func (o TransportCallAllOf11) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OtherFacility != nil {
		toSerialize["otherFacility"] = o.OtherFacility
	}
	return json.Marshal(toSerialize)
}

type NullableTransportCallAllOf11 struct {
	value *TransportCallAllOf11
	isSet bool
}

func (v NullableTransportCallAllOf11) Get() *TransportCallAllOf11 {
	return v.value
}

func (v *NullableTransportCallAllOf11) Set(val *TransportCallAllOf11) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf11) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf11) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf11(val *TransportCallAllOf11) *NullableTransportCallAllOf11 {
	return &NullableTransportCallAllOf11{value: val, isSet: true}
}

func (v NullableTransportCallAllOf11) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf11) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


