/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SealAllOf struct for SealAllOf
type SealAllOf struct {
	// Identifies a seal affixed to the container.
	SealNumber *string `json:"sealNumber,omitempty"`
}

// NewSealAllOf instantiates a new SealAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSealAllOf() *SealAllOf {
	this := SealAllOf{}
	return &this
}

// NewSealAllOfWithDefaults instantiates a new SealAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSealAllOfWithDefaults() *SealAllOf {
	this := SealAllOf{}
	return &this
}

// GetSealNumber returns the SealNumber field value if set, zero value otherwise.
func (o *SealAllOf) GetSealNumber() string {
	if o == nil || o.SealNumber == nil {
		var ret string
		return ret
	}
	return *o.SealNumber
}

// GetSealNumberOk returns a tuple with the SealNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SealAllOf) GetSealNumberOk() (*string, bool) {
	if o == nil || o.SealNumber == nil {
		return nil, false
	}
	return o.SealNumber, true
}

// HasSealNumber returns a boolean if a field has been set.
func (o *SealAllOf) HasSealNumber() bool {
	if o != nil && o.SealNumber != nil {
		return true
	}

	return false
}

// SetSealNumber gets a reference to the given string and assigns it to the SealNumber field.
func (o *SealAllOf) SetSealNumber(v string) {
	o.SealNumber = &v
}

func (o SealAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SealNumber != nil {
		toSerialize["sealNumber"] = o.SealNumber
	}
	return json.Marshal(toSerialize)
}

type NullableSealAllOf struct {
	value *SealAllOf
	isSet bool
}

func (v NullableSealAllOf) Get() *SealAllOf {
	return v.value
}

func (v *NullableSealAllOf) Set(val *SealAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSealAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSealAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSealAllOf(val *SealAllOf) *NullableSealAllOf {
	return &NullableSealAllOf{value: val, isSet: true}
}

func (v NullableSealAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSealAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


