/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// SealAllOf1 struct for SealAllOf1
type SealAllOf1 struct {
	SealSource *SealSource `json:"sealSource,omitempty"`
}

// NewSealAllOf1 instantiates a new SealAllOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSealAllOf1() *SealAllOf1 {
	this := SealAllOf1{}
	return &this
}

// NewSealAllOf1WithDefaults instantiates a new SealAllOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSealAllOf1WithDefaults() *SealAllOf1 {
	this := SealAllOf1{}
	return &this
}

// GetSealSource returns the SealSource field value if set, zero value otherwise.
func (o *SealAllOf1) GetSealSource() SealSource {
	if o == nil || o.SealSource == nil {
		var ret SealSource
		return ret
	}
	return *o.SealSource
}

// GetSealSourceOk returns a tuple with the SealSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SealAllOf1) GetSealSourceOk() (*SealSource, bool) {
	if o == nil || o.SealSource == nil {
		return nil, false
	}
	return o.SealSource, true
}

// HasSealSource returns a boolean if a field has been set.
func (o *SealAllOf1) HasSealSource() bool {
	if o != nil && o.SealSource != nil {
		return true
	}

	return false
}

// SetSealSource gets a reference to the given SealSource and assigns it to the SealSource field.
func (o *SealAllOf1) SetSealSource(v SealSource) {
	o.SealSource = &v
}

func (o SealAllOf1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SealSource != nil {
		toSerialize["sealSource"] = o.SealSource
	}
	return json.Marshal(toSerialize)
}

type NullableSealAllOf1 struct {
	value *SealAllOf1
	isSet bool
}

func (v NullableSealAllOf1) Get() *SealAllOf1 {
	return v.value
}

func (v *NullableSealAllOf1) Set(val *SealAllOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableSealAllOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableSealAllOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSealAllOf1(val *SealAllOf1) *NullableSealAllOf1 {
	return &NullableSealAllOf1{value: val, isSet: true}
}

func (v NullableSealAllOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSealAllOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


