/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org.  <i>Please note that shipment events and subscription management are not covered yet by CMA CGM API.</i>  <br> This API is accessible through <ul> <li> <b> Public </b> connection (authentication with API Key): this allows to retrieve standard equipment moves (e.g. ready to be loaded, discharged), Transhipment moves (e.g. discharged and re-loaded onboard) and planned vessel departure and arrival dates. </li> <li> <b> Private </b> connection (authentication with Oauth2 client credentials): this allows to retrieve additional private events such as actual rail and ramp moves, planned departure and arrival dates for inland moves. These private events are available only if you (or your end customer) are identified on the booking as: Booking Party, Deciding Party, Consignee, Notifier or Shipper. </li> </ul> </br> For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BaseTransportEventAllOf3 struct for BaseTransportEventAllOf3
type BaseTransportEventAllOf3 struct {
	// Reason code for the delay. The SMDG-Delay-Reason-Codes are used for this attribute. The code list can be found at http://www.smdg.org/smdg-code-lists/
	DelayReasonCode *string `json:"delayReasonCode,omitempty"`
}

// NewBaseTransportEventAllOf3 instantiates a new BaseTransportEventAllOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseTransportEventAllOf3() *BaseTransportEventAllOf3 {
	this := BaseTransportEventAllOf3{}
	return &this
}

// NewBaseTransportEventAllOf3WithDefaults instantiates a new BaseTransportEventAllOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseTransportEventAllOf3WithDefaults() *BaseTransportEventAllOf3 {
	this := BaseTransportEventAllOf3{}
	return &this
}

// GetDelayReasonCode returns the DelayReasonCode field value if set, zero value otherwise.
func (o *BaseTransportEventAllOf3) GetDelayReasonCode() string {
	if o == nil || o.DelayReasonCode == nil {
		var ret string
		return ret
	}
	return *o.DelayReasonCode
}

// GetDelayReasonCodeOk returns a tuple with the DelayReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTransportEventAllOf3) GetDelayReasonCodeOk() (*string, bool) {
	if o == nil || o.DelayReasonCode == nil {
		return nil, false
	}
	return o.DelayReasonCode, true
}

// HasDelayReasonCode returns a boolean if a field has been set.
func (o *BaseTransportEventAllOf3) HasDelayReasonCode() bool {
	if o != nil && o.DelayReasonCode != nil {
		return true
	}

	return false
}

// SetDelayReasonCode gets a reference to the given string and assigns it to the DelayReasonCode field.
func (o *BaseTransportEventAllOf3) SetDelayReasonCode(v string) {
	o.DelayReasonCode = &v
}

func (o BaseTransportEventAllOf3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DelayReasonCode != nil {
		toSerialize["delayReasonCode"] = o.DelayReasonCode
	}
	return json.Marshal(toSerialize)
}

type NullableBaseTransportEventAllOf3 struct {
	value *BaseTransportEventAllOf3
	isSet bool
}

func (v NullableBaseTransportEventAllOf3) Get() *BaseTransportEventAllOf3 {
	return v.value
}

func (v *NullableBaseTransportEventAllOf3) Set(val *BaseTransportEventAllOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseTransportEventAllOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseTransportEventAllOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseTransportEventAllOf3(val *BaseTransportEventAllOf3) *NullableBaseTransportEventAllOf3 {
	return &NullableBaseTransportEventAllOf3{value: val, isSet: true}
}

func (v NullableBaseTransportEventAllOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseTransportEventAllOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
