/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BaseTransportEventAllOf2 struct for BaseTransportEventAllOf2
type BaseTransportEventAllOf2 struct {
	TransportEventTypeCode *TransportEventTypeCode `json:"transportEventTypeCode,omitempty"`
}

// NewBaseTransportEventAllOf2 instantiates a new BaseTransportEventAllOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseTransportEventAllOf2() *BaseTransportEventAllOf2 {
	this := BaseTransportEventAllOf2{}
	return &this
}

// NewBaseTransportEventAllOf2WithDefaults instantiates a new BaseTransportEventAllOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseTransportEventAllOf2WithDefaults() *BaseTransportEventAllOf2 {
	this := BaseTransportEventAllOf2{}
	return &this
}

// GetTransportEventTypeCode returns the TransportEventTypeCode field value if set, zero value otherwise.
func (o *BaseTransportEventAllOf2) GetTransportEventTypeCode() TransportEventTypeCode {
	if o == nil || o.TransportEventTypeCode == nil {
		var ret TransportEventTypeCode
		return ret
	}
	return *o.TransportEventTypeCode
}

// GetTransportEventTypeCodeOk returns a tuple with the TransportEventTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTransportEventAllOf2) GetTransportEventTypeCodeOk() (*TransportEventTypeCode, bool) {
	if o == nil || o.TransportEventTypeCode == nil {
		return nil, false
	}
	return o.TransportEventTypeCode, true
}

// HasTransportEventTypeCode returns a boolean if a field has been set.
func (o *BaseTransportEventAllOf2) HasTransportEventTypeCode() bool {
	if o != nil && o.TransportEventTypeCode != nil {
		return true
	}

	return false
}

// SetTransportEventTypeCode gets a reference to the given TransportEventTypeCode and assigns it to the TransportEventTypeCode field.
func (o *BaseTransportEventAllOf2) SetTransportEventTypeCode(v TransportEventTypeCode) {
	o.TransportEventTypeCode = &v
}

func (o BaseTransportEventAllOf2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TransportEventTypeCode != nil {
		toSerialize["transportEventTypeCode"] = o.TransportEventTypeCode
	}
	return json.Marshal(toSerialize)
}

type NullableBaseTransportEventAllOf2 struct {
	value *BaseTransportEventAllOf2
	isSet bool
}

func (v NullableBaseTransportEventAllOf2) Get() *BaseTransportEventAllOf2 {
	return v.value
}

func (v *NullableBaseTransportEventAllOf2) Set(val *BaseTransportEventAllOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseTransportEventAllOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseTransportEventAllOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseTransportEventAllOf2(val *BaseTransportEventAllOf2) *NullableBaseTransportEventAllOf2 {
	return &NullableBaseTransportEventAllOf2{value: val, isSet: true}
}

func (v NullableBaseTransportEventAllOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseTransportEventAllOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


