/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TransportCall struct for TransportCall
type TransportCall struct {
	// The unique identifier for a transport call
	TransportCallID string `json:"transportCallID"`
	// The code of the service for which the schedule details are published.
	CarrierServiceCode *string `json:"carrierServiceCode,omitempty"`
	// The vessel operator-specific identifier of the Voyage. In case there are multiple voyages the export voyage is chosen.
	// Deprecated
	CarrierVoyageNumber interface{} `json:"carrierVoyageNumber,omitempty"`
	// The vessel operator-specific identifier of the export Voyage.
	ExportVoyageNumber *string `json:"exportVoyageNumber,omitempty"`
	// The vessel operator-specific identifier of the import Voyage.
	ImportVoyageNumber *string `json:"importVoyageNumber,omitempty"`
	// Transport operator&apos;s key that uniquely identifies each individual call. This key is essential to distinguish between two separate calls at the same location within one voyage.
	TransportCallSequenceNumber *int32 `json:"transportCallSequenceNumber,omitempty"`
	// The UN Location code specifying where the place is located.
	UNLocationCode *string `json:"UNLocationCode,omitempty"`
	// The code used for identifying the specific facility. This code does <b>not</b> include the UN Location Code.
	FacilityCode *string `json:"facilityCode,omitempty"`
	FacilityCodeListProvider *FacilityCodeListProvider `json:"facilityCodeListProvider,omitempty"`
	FacilityTypeCode *FacilityTypeCodeTRN `json:"facilityTypeCode,omitempty"`
	// An alternative way to capture the facility when no standardized DCSA facility code can be found.
	OtherFacility *string `json:"otherFacility,omitempty"`
	ModeOfTransport ModeOfTransport `json:"modeOfTransport"`
	Location NullableLocation `json:"location,omitempty"`
	Vessel *Vessel `json:"vessel,omitempty"`
}

// NewTransportCall instantiates a new TransportCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCall(transportCallID string, modeOfTransport ModeOfTransport) *TransportCall {
	this := TransportCall{}
	this.TransportCallID = transportCallID
	this.ModeOfTransport = modeOfTransport
	return &this
}

// NewTransportCallWithDefaults instantiates a new TransportCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallWithDefaults() *TransportCall {
	this := TransportCall{}
	return &this
}

// GetTransportCallID returns the TransportCallID field value
func (o *TransportCall) GetTransportCallID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportCallID
}

// GetTransportCallIDOk returns a tuple with the TransportCallID field value
// and a boolean to check if the value has been set.
func (o *TransportCall) GetTransportCallIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportCallID, true
}

// SetTransportCallID sets field value
func (o *TransportCall) SetTransportCallID(v string) {
	o.TransportCallID = v
}

// GetCarrierServiceCode returns the CarrierServiceCode field value if set, zero value otherwise.
func (o *TransportCall) GetCarrierServiceCode() string {
	if o == nil || o.CarrierServiceCode == nil {
		var ret string
		return ret
	}
	return *o.CarrierServiceCode
}

// GetCarrierServiceCodeOk returns a tuple with the CarrierServiceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetCarrierServiceCodeOk() (*string, bool) {
	if o == nil || o.CarrierServiceCode == nil {
		return nil, false
	}
	return o.CarrierServiceCode, true
}

// HasCarrierServiceCode returns a boolean if a field has been set.
func (o *TransportCall) HasCarrierServiceCode() bool {
	if o != nil && o.CarrierServiceCode != nil {
		return true
	}

	return false
}

// SetCarrierServiceCode gets a reference to the given string and assigns it to the CarrierServiceCode field.
func (o *TransportCall) SetCarrierServiceCode(v string) {
	o.CarrierServiceCode = &v
}

// GetCarrierVoyageNumber returns the CarrierVoyageNumber field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *TransportCall) GetCarrierVoyageNumber() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CarrierVoyageNumber
}

// GetCarrierVoyageNumberOk returns a tuple with the CarrierVoyageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *TransportCall) GetCarrierVoyageNumberOk() (*interface{}, bool) {
	if o == nil || o.CarrierVoyageNumber == nil {
		return nil, false
	}
	return &o.CarrierVoyageNumber, true
}

// HasCarrierVoyageNumber returns a boolean if a field has been set.
func (o *TransportCall) HasCarrierVoyageNumber() bool {
	if o != nil && o.CarrierVoyageNumber != nil {
		return true
	}

	return false
}

// SetCarrierVoyageNumber gets a reference to the given interface{} and assigns it to the CarrierVoyageNumber field.
// Deprecated
func (o *TransportCall) SetCarrierVoyageNumber(v interface{}) {
	o.CarrierVoyageNumber = v
}

// GetExportVoyageNumber returns the ExportVoyageNumber field value if set, zero value otherwise.
func (o *TransportCall) GetExportVoyageNumber() string {
	if o == nil || o.ExportVoyageNumber == nil {
		var ret string
		return ret
	}
	return *o.ExportVoyageNumber
}

// GetExportVoyageNumberOk returns a tuple with the ExportVoyageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetExportVoyageNumberOk() (*string, bool) {
	if o == nil || o.ExportVoyageNumber == nil {
		return nil, false
	}
	return o.ExportVoyageNumber, true
}

// HasExportVoyageNumber returns a boolean if a field has been set.
func (o *TransportCall) HasExportVoyageNumber() bool {
	if o != nil && o.ExportVoyageNumber != nil {
		return true
	}

	return false
}

// SetExportVoyageNumber gets a reference to the given string and assigns it to the ExportVoyageNumber field.
func (o *TransportCall) SetExportVoyageNumber(v string) {
	o.ExportVoyageNumber = &v
}

// GetImportVoyageNumber returns the ImportVoyageNumber field value if set, zero value otherwise.
func (o *TransportCall) GetImportVoyageNumber() string {
	if o == nil || o.ImportVoyageNumber == nil {
		var ret string
		return ret
	}
	return *o.ImportVoyageNumber
}

// GetImportVoyageNumberOk returns a tuple with the ImportVoyageNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetImportVoyageNumberOk() (*string, bool) {
	if o == nil || o.ImportVoyageNumber == nil {
		return nil, false
	}
	return o.ImportVoyageNumber, true
}

// HasImportVoyageNumber returns a boolean if a field has been set.
func (o *TransportCall) HasImportVoyageNumber() bool {
	if o != nil && o.ImportVoyageNumber != nil {
		return true
	}

	return false
}

// SetImportVoyageNumber gets a reference to the given string and assigns it to the ImportVoyageNumber field.
func (o *TransportCall) SetImportVoyageNumber(v string) {
	o.ImportVoyageNumber = &v
}

// GetTransportCallSequenceNumber returns the TransportCallSequenceNumber field value if set, zero value otherwise.
func (o *TransportCall) GetTransportCallSequenceNumber() int32 {
	if o == nil || o.TransportCallSequenceNumber == nil {
		var ret int32
		return ret
	}
	return *o.TransportCallSequenceNumber
}

// GetTransportCallSequenceNumberOk returns a tuple with the TransportCallSequenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetTransportCallSequenceNumberOk() (*int32, bool) {
	if o == nil || o.TransportCallSequenceNumber == nil {
		return nil, false
	}
	return o.TransportCallSequenceNumber, true
}

// HasTransportCallSequenceNumber returns a boolean if a field has been set.
func (o *TransportCall) HasTransportCallSequenceNumber() bool {
	if o != nil && o.TransportCallSequenceNumber != nil {
		return true
	}

	return false
}

// SetTransportCallSequenceNumber gets a reference to the given int32 and assigns it to the TransportCallSequenceNumber field.
func (o *TransportCall) SetTransportCallSequenceNumber(v int32) {
	o.TransportCallSequenceNumber = &v
}

// GetUNLocationCode returns the UNLocationCode field value if set, zero value otherwise.
func (o *TransportCall) GetUNLocationCode() string {
	if o == nil || o.UNLocationCode == nil {
		var ret string
		return ret
	}
	return *o.UNLocationCode
}

// GetUNLocationCodeOk returns a tuple with the UNLocationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetUNLocationCodeOk() (*string, bool) {
	if o == nil || o.UNLocationCode == nil {
		return nil, false
	}
	return o.UNLocationCode, true
}

// HasUNLocationCode returns a boolean if a field has been set.
func (o *TransportCall) HasUNLocationCode() bool {
	if o != nil && o.UNLocationCode != nil {
		return true
	}

	return false
}

// SetUNLocationCode gets a reference to the given string and assigns it to the UNLocationCode field.
func (o *TransportCall) SetUNLocationCode(v string) {
	o.UNLocationCode = &v
}

// GetFacilityCode returns the FacilityCode field value if set, zero value otherwise.
func (o *TransportCall) GetFacilityCode() string {
	if o == nil || o.FacilityCode == nil {
		var ret string
		return ret
	}
	return *o.FacilityCode
}

// GetFacilityCodeOk returns a tuple with the FacilityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetFacilityCodeOk() (*string, bool) {
	if o == nil || o.FacilityCode == nil {
		return nil, false
	}
	return o.FacilityCode, true
}

// HasFacilityCode returns a boolean if a field has been set.
func (o *TransportCall) HasFacilityCode() bool {
	if o != nil && o.FacilityCode != nil {
		return true
	}

	return false
}

// SetFacilityCode gets a reference to the given string and assigns it to the FacilityCode field.
func (o *TransportCall) SetFacilityCode(v string) {
	o.FacilityCode = &v
}

// GetFacilityCodeListProvider returns the FacilityCodeListProvider field value if set, zero value otherwise.
func (o *TransportCall) GetFacilityCodeListProvider() FacilityCodeListProvider {
	if o == nil || o.FacilityCodeListProvider == nil {
		var ret FacilityCodeListProvider
		return ret
	}
	return *o.FacilityCodeListProvider
}

// GetFacilityCodeListProviderOk returns a tuple with the FacilityCodeListProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetFacilityCodeListProviderOk() (*FacilityCodeListProvider, bool) {
	if o == nil || o.FacilityCodeListProvider == nil {
		return nil, false
	}
	return o.FacilityCodeListProvider, true
}

// HasFacilityCodeListProvider returns a boolean if a field has been set.
func (o *TransportCall) HasFacilityCodeListProvider() bool {
	if o != nil && o.FacilityCodeListProvider != nil {
		return true
	}

	return false
}

// SetFacilityCodeListProvider gets a reference to the given FacilityCodeListProvider and assigns it to the FacilityCodeListProvider field.
func (o *TransportCall) SetFacilityCodeListProvider(v FacilityCodeListProvider) {
	o.FacilityCodeListProvider = &v
}

// GetFacilityTypeCode returns the FacilityTypeCode field value if set, zero value otherwise.
func (o *TransportCall) GetFacilityTypeCode() FacilityTypeCodeTRN {
	if o == nil || o.FacilityTypeCode == nil {
		var ret FacilityTypeCodeTRN
		return ret
	}
	return *o.FacilityTypeCode
}

// GetFacilityTypeCodeOk returns a tuple with the FacilityTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetFacilityTypeCodeOk() (*FacilityTypeCodeTRN, bool) {
	if o == nil || o.FacilityTypeCode == nil {
		return nil, false
	}
	return o.FacilityTypeCode, true
}

// HasFacilityTypeCode returns a boolean if a field has been set.
func (o *TransportCall) HasFacilityTypeCode() bool {
	if o != nil && o.FacilityTypeCode != nil {
		return true
	}

	return false
}

// SetFacilityTypeCode gets a reference to the given FacilityTypeCodeTRN and assigns it to the FacilityTypeCode field.
func (o *TransportCall) SetFacilityTypeCode(v FacilityTypeCodeTRN) {
	o.FacilityTypeCode = &v
}

// GetOtherFacility returns the OtherFacility field value if set, zero value otherwise.
func (o *TransportCall) GetOtherFacility() string {
	if o == nil || o.OtherFacility == nil {
		var ret string
		return ret
	}
	return *o.OtherFacility
}

// GetOtherFacilityOk returns a tuple with the OtherFacility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetOtherFacilityOk() (*string, bool) {
	if o == nil || o.OtherFacility == nil {
		return nil, false
	}
	return o.OtherFacility, true
}

// HasOtherFacility returns a boolean if a field has been set.
func (o *TransportCall) HasOtherFacility() bool {
	if o != nil && o.OtherFacility != nil {
		return true
	}

	return false
}

// SetOtherFacility gets a reference to the given string and assigns it to the OtherFacility field.
func (o *TransportCall) SetOtherFacility(v string) {
	o.OtherFacility = &v
}

// GetModeOfTransport returns the ModeOfTransport field value
func (o *TransportCall) GetModeOfTransport() ModeOfTransport {
	if o == nil {
		var ret ModeOfTransport
		return ret
	}

	return o.ModeOfTransport
}

// GetModeOfTransportOk returns a tuple with the ModeOfTransport field value
// and a boolean to check if the value has been set.
func (o *TransportCall) GetModeOfTransportOk() (*ModeOfTransport, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModeOfTransport, true
}

// SetModeOfTransport sets field value
func (o *TransportCall) SetModeOfTransport(v ModeOfTransport) {
	o.ModeOfTransport = v
}

// GetLocation returns the Location field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TransportCall) GetLocation() Location {
	if o == nil || o.Location.Get() == nil {
		var ret Location
		return ret
	}
	return *o.Location.Get()
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransportCall) GetLocationOk() (*Location, bool) {
	if o == nil {
		return nil, false
	}
	return o.Location.Get(), o.Location.IsSet()
}

// HasLocation returns a boolean if a field has been set.
func (o *TransportCall) HasLocation() bool {
	if o != nil && o.Location.IsSet() {
		return true
	}

	return false
}

// SetLocation gets a reference to the given NullableLocation and assigns it to the Location field.
func (o *TransportCall) SetLocation(v Location) {
	o.Location.Set(&v)
}
// SetLocationNil sets the value for Location to be an explicit nil
func (o *TransportCall) SetLocationNil() {
	o.Location.Set(nil)
}

// UnsetLocation ensures that no value is present for Location, not even an explicit nil
func (o *TransportCall) UnsetLocation() {
	o.Location.Unset()
}

// GetVessel returns the Vessel field value if set, zero value otherwise.
func (o *TransportCall) GetVessel() Vessel {
	if o == nil || o.Vessel == nil {
		var ret Vessel
		return ret
	}
	return *o.Vessel
}

// GetVesselOk returns a tuple with the Vessel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCall) GetVesselOk() (*Vessel, bool) {
	if o == nil || o.Vessel == nil {
		return nil, false
	}
	return o.Vessel, true
}

// HasVessel returns a boolean if a field has been set.
func (o *TransportCall) HasVessel() bool {
	if o != nil && o.Vessel != nil {
		return true
	}

	return false
}

// SetVessel gets a reference to the given Vessel and assigns it to the Vessel field.
func (o *TransportCall) SetVessel(v Vessel) {
	o.Vessel = &v
}

func (o TransportCall) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["transportCallID"] = o.TransportCallID
	}
	if o.CarrierServiceCode != nil {
		toSerialize["carrierServiceCode"] = o.CarrierServiceCode
	}
	if o.CarrierVoyageNumber != nil {
		toSerialize["carrierVoyageNumber"] = o.CarrierVoyageNumber
	}
	if o.ExportVoyageNumber != nil {
		toSerialize["exportVoyageNumber"] = o.ExportVoyageNumber
	}
	if o.ImportVoyageNumber != nil {
		toSerialize["importVoyageNumber"] = o.ImportVoyageNumber
	}
	if o.TransportCallSequenceNumber != nil {
		toSerialize["transportCallSequenceNumber"] = o.TransportCallSequenceNumber
	}
	if o.UNLocationCode != nil {
		toSerialize["UNLocationCode"] = o.UNLocationCode
	}
	if o.FacilityCode != nil {
		toSerialize["facilityCode"] = o.FacilityCode
	}
	if o.FacilityCodeListProvider != nil {
		toSerialize["facilityCodeListProvider"] = o.FacilityCodeListProvider
	}
	if o.FacilityTypeCode != nil {
		toSerialize["facilityTypeCode"] = o.FacilityTypeCode
	}
	if o.OtherFacility != nil {
		toSerialize["otherFacility"] = o.OtherFacility
	}
	if true {
		toSerialize["modeOfTransport"] = o.ModeOfTransport
	}
	if o.Location.IsSet() {
		toSerialize["location"] = o.Location.Get()
	}
	if o.Vessel != nil {
		toSerialize["vessel"] = o.Vessel
	}
	return json.Marshal(toSerialize)
}

type NullableTransportCall struct {
	value *TransportCall
	isSet bool
}

func (v NullableTransportCall) Get() *TransportCall {
	return v.value
}

func (v *NullableTransportCall) Set(val *TransportCall) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCall) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCall(val *TransportCall) *NullableTransportCall {
	return &NullableTransportCall{value: val, isSet: true}
}

func (v NullableTransportCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


