/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TransportCallAllOf12 struct for TransportCallAllOf12
type TransportCallAllOf12 struct {
	ModeOfTransport *ModeOfTransport `json:"modeOfTransport,omitempty"`
}

// NewTransportCallAllOf12 instantiates a new TransportCallAllOf12 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf12() *TransportCallAllOf12 {
	this := TransportCallAllOf12{}
	return &this
}

// NewTransportCallAllOf12WithDefaults instantiates a new TransportCallAllOf12 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf12WithDefaults() *TransportCallAllOf12 {
	this := TransportCallAllOf12{}
	return &this
}

// GetModeOfTransport returns the ModeOfTransport field value if set, zero value otherwise.
func (o *TransportCallAllOf12) GetModeOfTransport() ModeOfTransport {
	if o == nil || o.ModeOfTransport == nil {
		var ret ModeOfTransport
		return ret
	}
	return *o.ModeOfTransport
}

// GetModeOfTransportOk returns a tuple with the ModeOfTransport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf12) GetModeOfTransportOk() (*ModeOfTransport, bool) {
	if o == nil || o.ModeOfTransport == nil {
		return nil, false
	}
	return o.ModeOfTransport, true
}

// HasModeOfTransport returns a boolean if a field has been set.
func (o *TransportCallAllOf12) HasModeOfTransport() bool {
	if o != nil && o.ModeOfTransport != nil {
		return true
	}

	return false
}

// SetModeOfTransport gets a reference to the given ModeOfTransport and assigns it to the ModeOfTransport field.
func (o *TransportCallAllOf12) SetModeOfTransport(v ModeOfTransport) {
	o.ModeOfTransport = &v
}

func (o TransportCallAllOf12) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ModeOfTransport != nil {
		toSerialize["modeOfTransport"] = o.ModeOfTransport
	}
	return json.Marshal(toSerialize)
}

type NullableTransportCallAllOf12 struct {
	value *TransportCallAllOf12
	isSet bool
}

func (v NullableTransportCallAllOf12) Get() *TransportCallAllOf12 {
	return v.value
}

func (v *NullableTransportCallAllOf12) Set(val *TransportCallAllOf12) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf12) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf12) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf12(val *TransportCallAllOf12) *NullableTransportCallAllOf12 {
	return &NullableTransportCallAllOf12{value: val, isSet: true}
}

func (v NullableTransportCallAllOf12) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf12) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
