/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// DocumentTypeCode The code to identify the type of information documentID points to. Can be one of the following values - CBR (Carrier Booking Request Reference) - BKG (Booking) - SHI (Shipping Instruction) - SRM (Shipment Release Message) - TRD (Transport Document) - ARN (Arrival Notice) - VGM (Verified Gross Mass) - CAS (Cargo Survey) - CUS (Customs Inspection) - DGD (Dangerous Goods Declaration) - OOG (Out of Gauge) More details can be found on <a href=\"https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/documenttypecodes.csv\">GitHub</a>
type DocumentTypeCode string

// List of documentTypeCode
const (
	DTC_CBR DocumentTypeCode = "CBR"
	DTC_BKG DocumentTypeCode = "BKG"
	DTC_SHI DocumentTypeCode = "SHI"
	DTC_SRM DocumentTypeCode = "SRM"
	DTC_TRD DocumentTypeCode = "TRD"
	DTC_ARN DocumentTypeCode = "ARN"
	DTC_VGM DocumentTypeCode = "VGM"
	DTC_CAS DocumentTypeCode = "CAS"
	DTC_CUS DocumentTypeCode = "CUS"
	DTC_DGD DocumentTypeCode = "DGD"
	DTC_OOG DocumentTypeCode = "OOG"
)

// All allowed values of DocumentTypeCode enum
var AllowedDocumentTypeCodeEnumValues = []DocumentTypeCode{
	"CBR",
	"BKG",
	"SHI",
	"SRM",
	"TRD",
	"ARN",
	"VGM",
	"CAS",
	"CUS",
	"DGD",
	"OOG",
}

func (v *DocumentTypeCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DocumentTypeCode(value)
	for _, existing := range AllowedDocumentTypeCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DocumentTypeCode", value)
}

// NewDocumentTypeCodeFromValue returns a pointer to a valid DocumentTypeCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDocumentTypeCodeFromValue(v string) (*DocumentTypeCode, error) {
	ev := DocumentTypeCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DocumentTypeCode: valid values are %v", v, AllowedDocumentTypeCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DocumentTypeCode) IsValid() bool {
	for _, existing := range AllowedDocumentTypeCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to documentTypeCode value
func (v DocumentTypeCode) Ptr() *DocumentTypeCode {
	return &v
}

type NullableDocumentTypeCode struct {
	value *DocumentTypeCode
	isSet bool
}

func (v NullableDocumentTypeCode) Get() *DocumentTypeCode {
	return v.value
}

func (v *NullableDocumentTypeCode) Set(val *DocumentTypeCode) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentTypeCode) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentTypeCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentTypeCode(val *DocumentTypeCode) *NullableDocumentTypeCode {
	return &NullableDocumentTypeCode{value: val, isSet: true}
}

func (v NullableDocumentTypeCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentTypeCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
