/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TransportCallAllOf8 struct for TransportCallAllOf8
type TransportCallAllOf8 struct {
	// The code used for identifying the specific facility. This code does <b>not</b> include the UN Location Code.
	FacilityCode *string `json:"facilityCode,omitempty"`
}

// NewTransportCallAllOf8 instantiates a new TransportCallAllOf8 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportCallAllOf8() *TransportCallAllOf8 {
	this := TransportCallAllOf8{}
	return &this
}

// NewTransportCallAllOf8WithDefaults instantiates a new TransportCallAllOf8 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportCallAllOf8WithDefaults() *TransportCallAllOf8 {
	this := TransportCallAllOf8{}
	return &this
}

// GetFacilityCode returns the FacilityCode field value if set, zero value otherwise.
func (o *TransportCallAllOf8) GetFacilityCode() string {
	if o == nil || o.FacilityCode == nil {
		var ret string
		return ret
	}
	return *o.FacilityCode
}

// GetFacilityCodeOk returns a tuple with the FacilityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportCallAllOf8) GetFacilityCodeOk() (*string, bool) {
	if o == nil || o.FacilityCode == nil {
		return nil, false
	}
	return o.FacilityCode, true
}

// HasFacilityCode returns a boolean if a field has been set.
func (o *TransportCallAllOf8) HasFacilityCode() bool {
	if o != nil && o.FacilityCode != nil {
		return true
	}

	return false
}

// SetFacilityCode gets a reference to the given string and assigns it to the FacilityCode field.
func (o *TransportCallAllOf8) SetFacilityCode(v string) {
	o.FacilityCode = &v
}

func (o TransportCallAllOf8) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FacilityCode != nil {
		toSerialize["facilityCode"] = o.FacilityCode
	}
	return json.Marshal(toSerialize)
}

type NullableTransportCallAllOf8 struct {
	value *TransportCallAllOf8
	isSet bool
}

func (v NullableTransportCallAllOf8) Get() *TransportCallAllOf8 {
	return v.value
}

func (v *NullableTransportCallAllOf8) Set(val *TransportCallAllOf8) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportCallAllOf8) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportCallAllOf8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportCallAllOf8(val *TransportCallAllOf8) *NullableTransportCallAllOf8 {
	return &NullableTransportCallAllOf8{value: val, isSet: true}
}

func (v NullableTransportCallAllOf8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportCallAllOf8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
