/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org.  <i>Please note that shipment events and subscription management are not covered yet by CMA CGM API.</i>  <br> This API is accessible through <ul> <li> <b> Public </b> connection (authentication with API Key): this allows to retrieve standard equipment moves (e.g. ready to be loaded, discharged), Transhipment moves (e.g. discharged and re-loaded onboard) and planned vessel departure and arrival dates. </li> <li> <b> Private </b> connection (authentication with Oauth2 client credentials): this allows to retrieve additional private events such as actual rail and ramp moves, planned departure and arrival dates for inland moves. These private events are available only if you (or your end customer) are identified on the booking as: Booking Party, Deciding Party, Consignee, Notifier or Shipper. </li> </ul> </br> For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CustomsReferences struct for CustomsReferences
type CustomsReferences struct {
	// The unique identifier for the equipment, which should follow the BIC ISO Container Identification Number where possible. According to ISO 6346, a container identification code consists of a 4-letter prefix and a 7-digit number (composed of a 3-letter owner code, a category identifier, a serial number, and a check-digit). If a container does not comply with ISO 6346, it is suggested to follow Recommendation
	EquipmentReference *string `json:"equipmentReference,omitempty"`
	// the customs reference for the container
	CustomsReference *string `json:"customsReference,omitempty"`
	// the customs reference date
	ReferenceDate *string `json:"referenceDate,omitempty"`
}

// NewCustomsReferences instantiates a new CustomsReferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomsReferences() *CustomsReferences {
	this := CustomsReferences{}
	return &this
}

// NewCustomsReferencesWithDefaults instantiates a new CustomsReferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomsReferencesWithDefaults() *CustomsReferences {
	this := CustomsReferences{}
	return &this
}

// GetEquipmentReference returns the EquipmentReference field value if set, zero value otherwise.
func (o *CustomsReferences) GetEquipmentReference() string {
	if o == nil || o.EquipmentReference == nil {
		var ret string
		return ret
	}
	return *o.EquipmentReference
}

// GetEquipmentReferenceOk returns a tuple with the EquipmentReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomsReferences) GetEquipmentReferenceOk() (*string, bool) {
	if o == nil || o.EquipmentReference == nil {
		return nil, false
	}
	return o.EquipmentReference, true
}

// HasEquipmentReference returns a boolean if a field has been set.
func (o *CustomsReferences) HasEquipmentReference() bool {
	if o != nil && o.EquipmentReference != nil {
		return true
	}

	return false
}

// SetEquipmentReference gets a reference to the given string and assigns it to the EquipmentReference field.
func (o *CustomsReferences) SetEquipmentReference(v string) {
	o.EquipmentReference = &v
}

// GetCustomsReference returns the CustomsReference field value if set, zero value otherwise.
func (o *CustomsReferences) GetCustomsReference() string {
	if o == nil || o.CustomsReference == nil {
		var ret string
		return ret
	}
	return *o.CustomsReference
}

// GetCustomsReferenceOk returns a tuple with the CustomsReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomsReferences) GetCustomsReferenceOk() (*string, bool) {
	if o == nil || o.CustomsReference == nil {
		return nil, false
	}
	return o.CustomsReference, true
}

// HasCustomsReference returns a boolean if a field has been set.
func (o *CustomsReferences) HasCustomsReference() bool {
	if o != nil && o.CustomsReference != nil {
		return true
	}

	return false
}

// SetCustomsReference gets a reference to the given string and assigns it to the CustomsReference field.
func (o *CustomsReferences) SetCustomsReference(v string) {
	o.CustomsReference = &v
}

// GetReferenceDate returns the ReferenceDate field value if set, zero value otherwise.
func (o *CustomsReferences) GetReferenceDate() string {
	if o == nil || o.ReferenceDate == nil {
		var ret string
		return ret
	}
	return *o.ReferenceDate
}

// GetReferenceDateOk returns a tuple with the ReferenceDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomsReferences) GetReferenceDateOk() (*string, bool) {
	if o == nil || o.ReferenceDate == nil {
		return nil, false
	}
	return o.ReferenceDate, true
}

// HasReferenceDate returns a boolean if a field has been set.
func (o *CustomsReferences) HasReferenceDate() bool {
	if o != nil && o.ReferenceDate != nil {
		return true
	}

	return false
}

// SetReferenceDate gets a reference to the given string and assigns it to the ReferenceDate field.
func (o *CustomsReferences) SetReferenceDate(v string) {
	o.ReferenceDate = &v
}

func (o CustomsReferences) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EquipmentReference != nil {
		toSerialize["equipmentReference"] = o.EquipmentReference
	}
	if o.CustomsReference != nil {
		toSerialize["customsReference"] = o.CustomsReference
	}
	if o.ReferenceDate != nil {
		toSerialize["referenceDate"] = o.ReferenceDate
	}
	return json.Marshal(toSerialize)
}

type NullableCustomsReferences struct {
	value *CustomsReferences
	isSet bool
}

func (v NullableCustomsReferences) Get() *CustomsReferences {
	return v.value
}

func (v *NullableCustomsReferences) Set(val *CustomsReferences) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomsReferences) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomsReferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomsReferences(val *CustomsReferences) *NullableCustomsReferences {
	return &NullableCustomsReferences{value: val, isSet: true}
}

func (v NullableCustomsReferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomsReferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
