/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// VesselAllOf3 struct for VesselAllOf3
type VesselAllOf3 struct {
	// A unique alphanumeric identity that belongs to the vessel and is assigned by the International Telecommunication Union (ITU). It consists of a threeletter alphanumeric prefix that indicates nationality, followed by one to four characters to identify the individual vessel. For instance, vessels registered under Denmark are assigned the prefix ranges 5PA-5QZ, OUAOZZ, and XPA-XPZ. The Call Sign changes whenever a vessel changes its flag.
	VesselCallSignNumber *string `json:"vesselCallSignNumber,omitempty"`
}

// NewVesselAllOf3 instantiates a new VesselAllOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVesselAllOf3() *VesselAllOf3 {
	this := VesselAllOf3{}
	return &this
}

// NewVesselAllOf3WithDefaults instantiates a new VesselAllOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVesselAllOf3WithDefaults() *VesselAllOf3 {
	this := VesselAllOf3{}
	return &this
}

// GetVesselCallSignNumber returns the VesselCallSignNumber field value if set, zero value otherwise.
func (o *VesselAllOf3) GetVesselCallSignNumber() string {
	if o == nil || o.VesselCallSignNumber == nil {
		var ret string
		return ret
	}
	return *o.VesselCallSignNumber
}

// GetVesselCallSignNumberOk returns a tuple with the VesselCallSignNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VesselAllOf3) GetVesselCallSignNumberOk() (*string, bool) {
	if o == nil || o.VesselCallSignNumber == nil {
		return nil, false
	}
	return o.VesselCallSignNumber, true
}

// HasVesselCallSignNumber returns a boolean if a field has been set.
func (o *VesselAllOf3) HasVesselCallSignNumber() bool {
	if o != nil && o.VesselCallSignNumber != nil {
		return true
	}

	return false
}

// SetVesselCallSignNumber gets a reference to the given string and assigns it to the VesselCallSignNumber field.
func (o *VesselAllOf3) SetVesselCallSignNumber(v string) {
	o.VesselCallSignNumber = &v
}

func (o VesselAllOf3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VesselCallSignNumber != nil {
		toSerialize["vesselCallSignNumber"] = o.VesselCallSignNumber
	}
	return json.Marshal(toSerialize)
}

type NullableVesselAllOf3 struct {
	value *VesselAllOf3
	isSet bool
}

func (v NullableVesselAllOf3) Get() *VesselAllOf3 {
	return v.value
}

func (v *NullableVesselAllOf3) Set(val *VesselAllOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableVesselAllOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableVesselAllOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVesselAllOf3(val *VesselAllOf3) *NullableVesselAllOf3 {
	return &NullableVesselAllOf3{value: val, isSet: true}
}

func (v NullableVesselAllOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVesselAllOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
