/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org.  <i>Please note that shipment events and subscription management are not covered yet by CMA CGM API.</i>  <br> This API is accessible through <ul> <li> <b> Public </b> connection (authentication with API Key): this allows to retrieve standard equipment moves (e.g. ready to be loaded, discharged), Transhipment moves (e.g. discharged and re-loaded onboard) and planned vessel departure and arrival dates. </li> <li> <b> Private </b> connection (authentication with Oauth2 client credentials): this allows to retrieve additional private events such as actual rail and ramp moves, planned departure and arrival dates for inland moves. These private events are available only if you (or your end customer) are identified on the booking as: Booking Party, Deciding Party, Consignee, Notifier or Shipper. </li> </ul> </br> For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// VesselAllOf4 struct for VesselAllOf4
type VesselAllOf4 struct {
	// The carrier who is in charge of the vessel operation based on either the SMDG or SCAC code lists
	VesselOperatorCarrierCode *string `json:"vesselOperatorCarrierCode,omitempty"`
}

// NewVesselAllOf4 instantiates a new VesselAllOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVesselAllOf4() *VesselAllOf4 {
	this := VesselAllOf4{}
	return &this
}

// NewVesselAllOf4WithDefaults instantiates a new VesselAllOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVesselAllOf4WithDefaults() *VesselAllOf4 {
	this := VesselAllOf4{}
	return &this
}

// GetVesselOperatorCarrierCode returns the VesselOperatorCarrierCode field value if set, zero value otherwise.
func (o *VesselAllOf4) GetVesselOperatorCarrierCode() string {
	if o == nil || o.VesselOperatorCarrierCode == nil {
		var ret string
		return ret
	}
	return *o.VesselOperatorCarrierCode
}

// GetVesselOperatorCarrierCodeOk returns a tuple with the VesselOperatorCarrierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VesselAllOf4) GetVesselOperatorCarrierCodeOk() (*string, bool) {
	if o == nil || o.VesselOperatorCarrierCode == nil {
		return nil, false
	}
	return o.VesselOperatorCarrierCode, true
}

// HasVesselOperatorCarrierCode returns a boolean if a field has been set.
func (o *VesselAllOf4) HasVesselOperatorCarrierCode() bool {
	if o != nil && o.VesselOperatorCarrierCode != nil {
		return true
	}

	return false
}

// SetVesselOperatorCarrierCode gets a reference to the given string and assigns it to the VesselOperatorCarrierCode field.
func (o *VesselAllOf4) SetVesselOperatorCarrierCode(v string) {
	o.VesselOperatorCarrierCode = &v
}

func (o VesselAllOf4) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VesselOperatorCarrierCode != nil {
		toSerialize["vesselOperatorCarrierCode"] = o.VesselOperatorCarrierCode
	}
	return json.Marshal(toSerialize)
}

type NullableVesselAllOf4 struct {
	value *VesselAllOf4
	isSet bool
}

func (v NullableVesselAllOf4) Get() *VesselAllOf4 {
	return v.value
}

func (v *NullableVesselAllOf4) Set(val *VesselAllOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableVesselAllOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableVesselAllOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVesselAllOf4(val *VesselAllOf4) *NullableVesselAllOf4 {
	return &NullableVesselAllOf4{value: val, isSet: true}
}

func (v NullableVesselAllOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVesselAllOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
