/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// BaseEventBodyAllOf2 struct for BaseEventBodyAllOf2
type BaseEventBodyAllOf2 struct {
	// The local date and time, where the event took place or when the event will take place, in ISO 8601 format.
	EventDateTime *time.Time `json:"eventDateTime,omitempty"`
}

// NewBaseEventBodyAllOf2 instantiates a new BaseEventBodyAllOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseEventBodyAllOf2() *BaseEventBodyAllOf2 {
	this := BaseEventBodyAllOf2{}
	return &this
}

// NewBaseEventBodyAllOf2WithDefaults instantiates a new BaseEventBodyAllOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseEventBodyAllOf2WithDefaults() *BaseEventBodyAllOf2 {
	this := BaseEventBodyAllOf2{}
	return &this
}

// GetEventDateTime returns the EventDateTime field value if set, zero value otherwise.
func (o *BaseEventBodyAllOf2) GetEventDateTime() time.Time {
	if o == nil || o.EventDateTime == nil {
		var ret time.Time
		return ret
	}
	return *o.EventDateTime
}

// GetEventDateTimeOk returns a tuple with the EventDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseEventBodyAllOf2) GetEventDateTimeOk() (*time.Time, bool) {
	if o == nil || o.EventDateTime == nil {
		return nil, false
	}
	return o.EventDateTime, true
}

// HasEventDateTime returns a boolean if a field has been set.
func (o *BaseEventBodyAllOf2) HasEventDateTime() bool {
	if o != nil && o.EventDateTime != nil {
		return true
	}

	return false
}

// SetEventDateTime gets a reference to the given time.Time and assigns it to the EventDateTime field.
func (o *BaseEventBodyAllOf2) SetEventDateTime(v time.Time) {
	o.EventDateTime = &v
}

func (o BaseEventBodyAllOf2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EventDateTime != nil {
		toSerialize["eventDateTime"] = o.EventDateTime
	}
	return json.Marshal(toSerialize)
}

type NullableBaseEventBodyAllOf2 struct {
	value *BaseEventBodyAllOf2
	isSet bool
}

func (v NullableBaseEventBodyAllOf2) Get() *BaseEventBodyAllOf2 {
	return v.value
}

func (v *NullableBaseEventBodyAllOf2) Set(val *BaseEventBodyAllOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseEventBodyAllOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseEventBodyAllOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseEventBodyAllOf2(val *BaseEventBodyAllOf2) *NullableBaseEventBodyAllOf2 {
	return &NullableBaseEventBodyAllOf2{value: val, isSet: true}
}

func (v NullableBaseEventBodyAllOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseEventBodyAllOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


