/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org. For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.0.3
Contact: ho.support-api@cma-cgm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BaseEventBodyAllOf1 struct for BaseEventBodyAllOf1
type BaseEventBodyAllOf1 struct {
	// Code for the event classifier. Values can vary depending on eventType
	EventClassifierCode *string `json:"eventClassifierCode,omitempty"`
}

// NewBaseEventBodyAllOf1 instantiates a new BaseEventBodyAllOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseEventBodyAllOf1() *BaseEventBodyAllOf1 {
	this := BaseEventBodyAllOf1{}
	return &this
}

// NewBaseEventBodyAllOf1WithDefaults instantiates a new BaseEventBodyAllOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseEventBodyAllOf1WithDefaults() *BaseEventBodyAllOf1 {
	this := BaseEventBodyAllOf1{}
	return &this
}

// GetEventClassifierCode returns the EventClassifierCode field value if set, zero value otherwise.
func (o *BaseEventBodyAllOf1) GetEventClassifierCode() string {
	if o == nil || o.EventClassifierCode == nil {
		var ret string
		return ret
	}
	return *o.EventClassifierCode
}

// GetEventClassifierCodeOk returns a tuple with the EventClassifierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseEventBodyAllOf1) GetEventClassifierCodeOk() (*string, bool) {
	if o == nil || o.EventClassifierCode == nil {
		return nil, false
	}
	return o.EventClassifierCode, true
}

// HasEventClassifierCode returns a boolean if a field has been set.
func (o *BaseEventBodyAllOf1) HasEventClassifierCode() bool {
	if o != nil && o.EventClassifierCode != nil {
		return true
	}

	return false
}

// SetEventClassifierCode gets a reference to the given string and assigns it to the EventClassifierCode field.
func (o *BaseEventBodyAllOf1) SetEventClassifierCode(v string) {
	o.EventClassifierCode = &v
}

func (o BaseEventBodyAllOf1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EventClassifierCode != nil {
		toSerialize["eventClassifierCode"] = o.EventClassifierCode
	}
	return json.Marshal(toSerialize)
}

type NullableBaseEventBodyAllOf1 struct {
	value *BaseEventBodyAllOf1
	isSet bool
}

func (v NullableBaseEventBodyAllOf1) Get() *BaseEventBodyAllOf1 {
	return v.value
}

func (v *NullableBaseEventBodyAllOf1) Set(val *BaseEventBodyAllOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseEventBodyAllOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseEventBodyAllOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseEventBodyAllOf1(val *BaseEventBodyAllOf1) *NullableBaseEventBodyAllOf1 {
	return &NullableBaseEventBodyAllOf1{value: val, isSet: true}
}

func (v NullableBaseEventBodyAllOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseEventBodyAllOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


