/*
Logistic Tracking service API - DCSA OpenAPI specification for Track & Trace v2.2.0

Managing and sending Shipment-, Transport- and Equipment-events and subscriptions for Track &amp; Trace (T&amp;T). API specification issued by DCSA.org.  <i>Please note that shipment events and subscription management are not covered yet by CMA CGM API.</i>  <br> This API is accessible through <ul> <li> <b> Public </b> connection (authentication with API Key): this allows to retrieve standard equipment moves (e.g. ready to be loaded, discharged), Transhipment moves (e.g. discharged and re-loaded onboard) and planned vessel departure and arrival dates. </li> <li> <b> Private </b> connection (authentication with Oauth2 client credentials): this allows to retrieve additional private events such as actual rail and ramp moves, planned departure and arrival dates for inland moves. These private events are available only if you (or your end customer) are identified on the booking as: Booking Party, Deciding Party, Consignee, Notifier or Shipper. </li> </ul> </br> For explanation to specific values or objects please refer to the <a href='https://dcsa.org/wp-content/uploads/2021/10/202108_DCSA_P1_Information-Model-v3.3_TNT22_Final.pdf'>Information Model v3.3</a> Polling can be done on the <b>GET /events</b> endPoint. DCSA version 2.2.0

API version: 1.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BaseEquipmentEventAllOf2 struct for BaseEquipmentEventAllOf2
type BaseEquipmentEventAllOf2 struct {
	EquipmentEventTypeCode *EquipmentEventTypeCode `json:"equipmentEventTypeCode,omitempty"`
}

// NewBaseEquipmentEventAllOf2 instantiates a new BaseEquipmentEventAllOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseEquipmentEventAllOf2() *BaseEquipmentEventAllOf2 {
	this := BaseEquipmentEventAllOf2{}
	return &this
}

// NewBaseEquipmentEventAllOf2WithDefaults instantiates a new BaseEquipmentEventAllOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseEquipmentEventAllOf2WithDefaults() *BaseEquipmentEventAllOf2 {
	this := BaseEquipmentEventAllOf2{}
	return &this
}

// GetEquipmentEventTypeCode returns the EquipmentEventTypeCode field value if set, zero value otherwise.
func (o *BaseEquipmentEventAllOf2) GetEquipmentEventTypeCode() EquipmentEventTypeCode {
	if o == nil || o.EquipmentEventTypeCode == nil {
		var ret EquipmentEventTypeCode
		return ret
	}
	return *o.EquipmentEventTypeCode
}

// GetEquipmentEventTypeCodeOk returns a tuple with the EquipmentEventTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseEquipmentEventAllOf2) GetEquipmentEventTypeCodeOk() (*EquipmentEventTypeCode, bool) {
	if o == nil || o.EquipmentEventTypeCode == nil {
		return nil, false
	}
	return o.EquipmentEventTypeCode, true
}

// HasEquipmentEventTypeCode returns a boolean if a field has been set.
func (o *BaseEquipmentEventAllOf2) HasEquipmentEventTypeCode() bool {
	if o != nil && o.EquipmentEventTypeCode != nil {
		return true
	}

	return false
}

// SetEquipmentEventTypeCode gets a reference to the given EquipmentEventTypeCode and assigns it to the EquipmentEventTypeCode field.
func (o *BaseEquipmentEventAllOf2) SetEquipmentEventTypeCode(v EquipmentEventTypeCode) {
	o.EquipmentEventTypeCode = &v
}

func (o BaseEquipmentEventAllOf2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EquipmentEventTypeCode != nil {
		toSerialize["equipmentEventTypeCode"] = o.EquipmentEventTypeCode
	}
	return json.Marshal(toSerialize)
}

type NullableBaseEquipmentEventAllOf2 struct {
	value *BaseEquipmentEventAllOf2
	isSet bool
}

func (v NullableBaseEquipmentEventAllOf2) Get() *BaseEquipmentEventAllOf2 {
	return v.value
}

func (v *NullableBaseEquipmentEventAllOf2) Set(val *BaseEquipmentEventAllOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseEquipmentEventAllOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseEquipmentEventAllOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseEquipmentEventAllOf2(val *BaseEquipmentEventAllOf2) *NullableBaseEquipmentEventAllOf2 {
	return &NullableBaseEquipmentEventAllOf2{value: val, isSet: true}
}

func (v NullableBaseEquipmentEventAllOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseEquipmentEventAllOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
